# Chapter 4
## NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.1 ms, sys: 5.65 ms, total: 20.8 ms
Wall time: 19.5 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 622 ms, sys: 151 ms, total: 772 ms
Wall time: 772 ms


## 4.1 The NumPy `ndarray`: A Multidemensional Array Object

In [4]:
import numpy as np

data = np.random.randn(2, 3)

data

array([[-0.22792923,  0.3344037 ,  1.31988232],
       [ 0.33106059, -0.13711185, -0.25833786]])

In [5]:
data * 10

array([[ -2.27929225,   3.34403697,  13.1988232 ],
       [  3.31060591,  -1.37111847,  -2.58337858]])

In [6]:
data + data

array([[-0.45585845,  0.66880739,  2.63976464],
       [ 0.66212118, -0.27422369, -0.51667572]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating `ndarray`s

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [10]:
multidimensional_data = [[1, 2, 3, 4], [5, 6, 7, 8]]
multidimensional_array = np.array(multidimensional_data)
multidimensional_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
multidimensional_array.ndim

2

In [12]:
multidimensional_array.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
multidimensional_array.dtype

dtype('int64')

In [15]:
arr = np.array([1, 2, 3])
other_arr = np.array(arr)
arr is other_arr

False

In [16]:
# np.asarray doesn't copy if input is already an ndarray
asarray_arr = np.asarray(arr)
asarray_arr is arr

True

In [17]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
np.empty((2, 3, 2))

array([[[  3.10503618e+231,  -3.11110047e+231],
        [  2.37663529e-312,   2.56761491e-312],
        [  8.48798317e-313,   9.33678148e-313]],

       [[  1.08221785e-312,   6.79038653e-313],
        [  8.70018275e-313,   3.85415159e-057],
        [  3.99910963e+252,   8.34404956e-309]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(15, 100, 2)

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81,
       83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
np.ones(10, dtype='float32')

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [25]:
np.ones_like(np.empty((2, 3, 2)), 'int')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [26]:
np.full(10, 100_000)

array([100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
       100000, 100000])

In [27]:
np.full((2, 10), 3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [28]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### Data Types for `ndarrays`

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [31]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [34]:
np.dtype('float32')

dtype('float32')

In [35]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr.dtype

dtype('int64')

In [37]:
float_arr = arr.astype(np.float64)

In [38]:
float_arr.dtype

dtype('float64')

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [40]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [41]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.dtype

dtype('<U4')

In [42]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [43]:
numeric_strings.astype(np.string_)

array([b'1.25', b'-9.6', b'42'],
      dtype='|S4')

In [44]:
int_array =np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype) # always creates a new array (a copy), even if the new dtype is the same as the old.

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [45]:
np.empty(8, dtype='u4')

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [48]:
arr = np.array([[1., 2, 3], [4, 5, 6]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [49]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [50]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [51]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [52]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [53]:
arr2 = np.array([[0., 4, 1], [7, 2, 12]])
arr2

array([[  0.,   4.,   1.],
       [  7.,   2.,  12.]])

In [54]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

### Basic Indexing and Slicing