# Chapter 4
## NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 12.9 ms, sys: 6.91 ms, total: 19.8 ms
Wall time: 23.4 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 609 ms, sys: 165 ms, total: 774 ms
Wall time: 773 ms


## 4.1 The NumPy `ndarray`: A Multidemensional Array Object

In [4]:
import numpy as np

data = np.random.randn(2, 3)

data

array([[-0.12059607,  1.46192377,  1.00547402],
       [-0.66232443,  0.08985345, -0.19951938]])

In [5]:
data * 10

array([[ -1.20596073,  14.61923772,  10.05474019],
       [ -6.62324433,   0.89853447,  -1.9951938 ]])

In [6]:
data + data

array([[-0.24119215,  2.92384754,  2.01094804],
       [-1.32464887,  0.17970689, -0.39903876]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

### Creating `ndarray`s

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [10]:
multidimensional_data = [[1, 2, 3, 4], [5, 6, 7, 8]]
multidimensional_array = np.array(multidimensional_data)
multidimensional_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
multidimensional_array.ndim

2

In [12]:
multidimensional_array.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
multidimensional_array.dtype

dtype('int64')

In [15]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
np.empty((2, 3, 2))

array([[[ -1.72723371e-077,   3.11108619e+231],
        [  2.37663529e-312,   2.56761491e-312],
        [  8.48798317e-313,   9.33678148e-313]],

       [[  1.08221785e-312,   6.79038653e-313],
        [  8.70018275e-313,   5.64054899e-062],
        [  3.99910963e+252,   8.34402697e-309]]])

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange(15, 100, 2)

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81,
       83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.ones(10, dtype='float32')

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [30]:
np.ones_like(np.empty((2, 3, 2)), 'int')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [31]:
np.full(10, 100_000)

array([100000, 100000, 100000, 100000, 100000, 100000, 100000, 100000,
       100000, 100000])

In [32]:
np.full((2, 10), 3)

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])