# Chapter 7
## Data Cleaning and Preparation

## 7.1 Handling Missing Data

In [3]:
import pandas as pd
import numpy as np

string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

In [6]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])

data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
# equivalent to:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna() # drops any row containing a missing value by default
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis=1, how='all') # or axis='columns'

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.677818       NaN       NaN
1 -0.802348       NaN       NaN
2 -1.667469       NaN -1.276721
3 -1.496449       NaN -0.328463
4 -0.766211 -0.186769  0.249714
5 -0.251390  0.238465  0.715977
6  1.841382 -1.330049 -1.294407

In [18]:
df.dropna()

0         1         2
4 -0.766211 -0.186769  0.249714
5 -0.251390  0.238465  0.715977
6  1.841382 -1.330049 -1.294407

In [19]:
df.dropna(thresh=2)

0         1         2
2 -1.667469       NaN -1.276721
3 -1.496449       NaN -0.328463
4 -0.766211 -0.186769  0.249714
5 -0.251390  0.238465  0.715977
6  1.841382 -1.330049 -1.294407

### Filling In Missing Data

In [20]:
df.fillna(0)

0         1         2
0  0.677818  0.000000  0.000000
1 -0.802348  0.000000  0.000000
2 -1.667469  0.000000 -1.276721
3 -1.496449  0.000000 -0.328463
4 -0.766211 -0.186769  0.249714
5 -0.251390  0.238465  0.715977
6  1.841382 -1.330049 -1.294407

In [21]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.677818  0.500000  0.000000
1 -0.802348  0.500000  0.000000
2 -1.667469  0.500000 -1.276721
3 -1.496449  0.500000 -0.328463
4 -0.766211 -0.186769  0.249714
5 -0.251390  0.238465  0.715977
6  1.841382 -1.330049 -1.294407

In [22]:
_ = df.fillna(0, inplace=True)

In [23]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.224266 -0.273275 -0.896235
1 -1.441220 -0.754298  0.506612
2 -0.570685       NaN -0.443217
3 -0.871855       NaN -0.091270
4  0.907545       NaN       NaN
5 -0.740900       NaN       NaN

In [24]:
df.fillna(method='ffill')

0         1         2
0  0.224266 -0.273275 -0.896235
1 -1.441220 -0.754298  0.506612
2 -0.570685 -0.754298 -0.443217
3 -0.871855 -0.754298 -0.091270
4  0.907545 -0.754298 -0.091270
5 -0.740900 -0.754298 -0.091270

In [25]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.224266 -0.273275 -0.896235
1 -1.441220 -0.754298  0.506612
2 -0.570685 -0.754298 -0.443217
3 -0.871855 -0.754298 -0.091270
4  0.907545       NaN -0.091270
5 -0.740900       NaN -0.091270

In [30]:
df.fillna(method='ffill', axis=1)

0         1         2
0  0.224266 -0.273275 -0.896235
1 -1.441220 -0.754298  0.506612
2 -0.570685 -0.570685 -0.443217
3 -0.871855 -0.871855 -0.091270
4  0.907545  0.907545  0.907545
5 -0.740900 -0.740900 -0.740900

In [26]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Data Transformation

### Removing Duplicates

In [32]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [33]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [34]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [35]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [36]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [37]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [38]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon',
}

lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [48]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [49]:
# equivalently, we could pass a function:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [50]:
data = pd.Series([1., -999, 2, -999, -1000, 3])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [53]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [57]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
# this is different from `data.map` in that map will return NaN for any value not in the provided map:
data.map({-999: np.nan, -1000: 0})

0    NaN
1    NaN
2    NaN
3    NaN
4    0.0
5    NaN
dtype: float64

### Renaming Axis Indexes

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [60]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [61]:
# create a transformed version of the dataset without modifying the original with `rename`:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [66]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [67]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'}, inplace=True)

In [68]:
data

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [69]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
# divide into bins of 18-25, 26-35, 36-60, 61+
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [70]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [71]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [73]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [74]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [75]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [80]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.73, 0.96], (0.035, 0.27], (0.035, 0.27], (0.27, 0.5], (0.5, 0.73], ..., (0.73, 0.96], (0.5, 0.73], (0.73, 0.96], (0.73, 0.96], (0.035, 0.27]]
Length: 20
Categories (4, interval[float64]): [(0.035, 0.27] < (0.27, 0.5] < (0.5, 0.73] < (0.73, 0.96]]

In [91]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(0.0385, 0.662], (-2.791, -0.611], (0.0385, 0.662], (0.0385, 0.662], (0.662, 2.747], ..., (0.662, 2.747], (-0.611, 0.0385], (0.662, 2.747], (0.0385, 0.662], (0.662, 2.747]]
Length: 1000
Categories (4, interval[float64]): [(-2.791, -0.611] < (-0.611, 0.0385] < (0.0385, 0.662] < (0.662, 2.747]]

In [92]:
pd.value_counts(cats).sort_index()

(-2.791, -0.611]    250
(-0.611, 0.0385]    250
(0.0385, 0.662]     250
(0.662, 2.747]      250
dtype: int64

In [93]:
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]) # provide your own quantiles
cats

[(0.0385, 1.218], (-2.791, -1.153], (0.0385, 1.218], (0.0385, 1.218], (0.0385, 1.218], ..., (0.0385, 1.218], (-1.153, 0.0385], (1.218, 2.747], (0.0385, 1.218], (0.0385, 1.218]]
Length: 1000
Categories (4, interval[float64]): [(-2.791, -1.153] < (-1.153, 0.0385] < (0.0385, 1.218] < (1.218, 2.747]]

In [94]:
pd.value_counts(cats).sort_index()

(-2.791, -1.153]    100
(-1.153, 0.0385]    400
(0.0385, 1.218]     400
(1.218, 2.747]      100
dtype: int64

### Detecting and Filtering Outliers

In [98]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027183    -0.014667    -0.003279    -0.003853
std       1.001394     0.954830     1.039178     0.988822
min      -2.957640    -3.672808    -3.476333    -2.871956
25%      -0.716425    -0.638646    -0.678701    -0.670874
50%      -0.037395    -0.038989    -0.030877    -0.016005
75%       0.613410     0.608122     0.709502     0.623403
max       3.197838     3.748862     3.204510     3.200855

In [99]:
col = data[2]
col[np.abs(col) > 3]

38     3.204510
71    -3.086001
467   -3.476333
546    3.113941
623   -3.182405
999    3.083512
Name: 2, dtype: float64

In [104]:
(np.abs(data) > 3).any() # _columns_ with any abs values > 3

0    True
1    True
2    True
3    True
dtype: bool

In [107]:
(np.abs(data) > 3).any(1).head() # _rows_ with any abs values > 3

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [108]:
data[(np.abs(data) > 3).any(1)] # select all rows having a value > 3 or < -3

0         1         2         3
38  -0.151967 -0.008717  3.204510  0.062273
50  -1.452436  1.107244  1.762790  3.086029
71   1.604088 -0.131247 -3.086001 -0.219768
169  0.437402 -0.435468 -0.475748  3.200855
467  1.383365 -0.457175 -3.476333 -0.534004
546  0.220329  1.803374  3.113941 -0.383594
554 -0.410258 -3.672808 -0.019907 -1.340488
559 -0.165817  3.748862  0.508536 -2.493792
575  3.197838  0.460088 -1.450897  2.053964
623 -0.465199  1.394653 -3.182405 -1.482761
889 -0.170810 -0.469271 -0.469022  3.033513
999  1.136231 -0.402080  3.083512  0.631335

In [110]:
data[np.abs(data) > 3] = np.sign(data) * 3 # cap values outside the interval [-3, 3]
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.027380    -0.014743    -0.002936    -0.004173
std       1.000776     0.949813     1.035701     0.987823
min      -2.957640    -3.000000    -3.000000    -2.871956
25%      -0.716425    -0.638646    -0.678701    -0.670874
50%      -0.037395    -0.038989    -0.030877    -0.016005
75%       0.613410     0.608122     0.709502     0.623403
max       3.000000     3.000000     3.000000     3.000000

In [111]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0  1.0
1  1.0 -1.0  1.0  1.0
2  1.0  1.0 -1.0  1.0
3  1.0 -1.0  1.0  1.0
4 -1.0  1.0  1.0  1.0

### Permutation and Random Sampling

In [113]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([4, 0, 2, 3, 1])

In [114]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [115]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [117]:
df.iloc[sampler] # equivalent to `take`

0   1   2   3
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7

In [124]:
# sample _without_ replacement:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [122]:
# sample _with_ replacement:
df.sample(n=10, replace=True)

0   1   2   3
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
1   4   5   6   7
4  16  17  18  19
1   4   5   6   7
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3

### Computing Indicator/Dummy Variables

In [125]:
df = pd.DataFrame({'key': list('bbacab'), 'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [126]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [130]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [132]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::', header=None, names=mnames)
movies[:10]

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [142]:
genres = pd.unique([genre for x in movies.genres for genre in x.split('|')])
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [143]:
# Compute indicator DataFrame
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [144]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [147]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [148]:
movies_w_indic = movies.join(dummies.add_prefix('Genre_'))
movies_w_indic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [149]:
# Combine `get_dummies` with a discretization function like `cut`
np.random.seed(12345)
values = np.random.rand(10)
values

array([ 0.92961609,  0.31637555,  0.18391881,  0.20456028,  0.56772503,
        0.5955447 ,  0.96451452,  0.6531771 ,  0.74890664,  0.65356987])

In [155]:
bins = np.arange(0, 1.2, 0.2)
bins

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [156]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 String Manipulation

### String Object Methods

In [157]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [158]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [159]:
'::'.join(pieces)

'a::b::guido'

In [160]:
'guido' in val

True

In [161]:
val.index(',')

1

In [164]:
val.find(':') # `val.index(':')` would raise a ValueError

-1

In [165]:
val.count(',')

2

In [166]:
val.replace(',', '::')

'a::b:: guido'

In [167]:
val.replace(',', '')

'ab guido'

### Regular Expressions

In [172]:
import re
text = "foo   bar\t baz  \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [173]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [174]:
regex.findall(text)

['   ', '\t ', '  \t']

In [175]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [176]:
m = regex.search(text)
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [177]:
text[m.start():m.end()]

'dave@google.com'

In [179]:
print(regex.match(text))
# `None` is returned, as `match` only matches if the pattern occurs at the start of the string

None


In [180]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [181]:
segmented_pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(segmented_pattern, flags=re.IGNORECASE)
m = regex.match('wesm@bright.net')
m.groups() # returns a tuple of the pattern components 

('wesm', 'bright', 'net')

In [182]:
regex.findall(text) # returns a list of tuples when the pattern has groups

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [186]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



### Vectorized String Functions in pandas

In [187]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [188]:
data.isnull()

Dave     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [190]:
data.str.contains('gmail')

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object

In [192]:
segmented_pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [193]:
data.str.findall(segmented_pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Rob        [(rob, gmail, com)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [194]:
matches = data.str.match(segmented_pattern, flags=re.IGNORECASE)
matches

Dave     True
Rob      True
Steve    True
Wes       NaN
dtype: object

In [196]:
matches.str.get(1)

Dave    NaN
Rob     NaN
Steve   NaN
Wes     NaN
dtype: float64

In [197]:
matches.str[0]

Dave    NaN
Rob     NaN
Steve   NaN
Wes     NaN
dtype: float64

In [198]:
data.str[:5]

Dave     dave@
Rob      rob@g
Steve    steve
Wes        NaN
dtype: object

In [234]:
data.str.contains(r'\w+')

Dave     True
Rob      True
Steve    True
Wes       NaN
dtype: object

In [235]:
data.str.findall(r'\w+')

Dave     [dave, google, com]
Rob        [rob, gmail, com]
Steve    [steve, gmail, com]
Wes                      NaN
dtype: object

In [236]:
data.str.findall(re.compile(r'\w+'))

Dave     [dave, google, com]
Rob        [rob, gmail, com]
Steve    [steve, gmail, com]
Wes                      NaN
dtype: object

In [243]:
data.str.replace(r'(\w+)', '')

Dave      @.
Rob       @.
Steve     @.
Wes      NaN
dtype: object