## Appendix A
# Advanced NumPy

## A.1 `ndarray` Object Internals

In [1]:
import numpy as np
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

np.ones((10, 5)).shape

(10, 5)

In [2]:
np.ones((3, 4, 5), dtype=np.float64).strides # number of bytes to 'step' in order to advance an element along each dimension

(160, 40, 8)

### NumPy `dtype` Hierarchy

In [3]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [4]:
np.issubdtype(floats.dtype, np.floating)

True

In [5]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [6]:
np.issubdtype(ints.dtype, np.number)

True

In [7]:
np.issubdtype(floats.dtype, float)

True

In [8]:
np.issubdtype(ints.dtype, int)

False

### Reshaping Arrays

In [9]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [11]:
_.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr = np.arange(15)
arr.reshape((5, -1)) # value used for the column dimension will be inferred from the data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
np.arange(15).reshape((5, -1)).reshape((3, -1)).reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [15]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
arr.ravel() # opposite of `reshape`

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr.flatten() # _always_ returns a copy of the data, even if results are contiguous in th original array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C Versus Fortran Order

In [19]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
arr.ravel('F') # traverse higher dimensions _last_ (e.g. axis 0 before advancing on axis 1)

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [22]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.concatenate([arr1, arr2]) # axis=0 is default

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [25]:
np.vstack((arr1, arr2)) # equivalent to concatenate(..., axis=0) above

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.hstack((arr1, arr2)) # equivalent to concatenate(..., axis=1) above

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
arr = np.random.randn(5, 2)
arr

array([[-0.692, -0.997],
       [-1.253,  1.314],
       [-0.379,  0.541],
       [-1.82 ,  0.077],
       [-0.658, -0.057]])

In [28]:
first, second, third = np.split(arr, [1, 3])

In [29]:
first

array([[-0.692, -0.997]])

In [30]:
second

array([[-1.253,  1.314],
       [-0.379,  0.541]])

In [31]:
third

array([[-1.82 ,  0.077],
       [-0.658, -0.057]])

In [32]:
first, second = np.split(arr, [1], axis=1)

In [33]:
first

array([[-0.692],
       [-1.253],
       [-0.379],
       [-1.82 ],
       [-0.658]])

In [34]:
second

array([[-0.997],
       [ 1.314],
       [ 0.541],
       [ 0.077],
       [-0.057]])

#### Stacking helpers: `r_` and `c_`

In [35]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.   ,  1.   ],
       [ 2.   ,  3.   ],
       [ 4.   ,  5.   ],
       [ 0.648, -1.081],
       [ 0.034,  1.378],
       [-0.896,  2.514]])

In [36]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.   ,  1.   ,  0.   ],
       [ 2.   ,  3.   ,  1.   ],
       [ 4.   ,  5.   ,  2.   ],
       [ 0.648, -1.081,  3.   ],
       [ 0.034,  1.378,  4.   ],
       [-0.896,  2.514,  5.   ]])

In [37]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: `tile` and `repeat`

In [38]:
arr = np.arange(3)
arr.repeat(3) # _broadcasting_ often fills this need better

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [39]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [40]:
arr = np.random.randn(2, 2)
arr

array([[ 0.295,  1.506],
       [-0.18 ,  0.324]])

In [41]:
arr.repeat(2, axis=0)

array([[ 0.295,  1.506],
       [ 0.295,  1.506],
       [-0.18 ,  0.324],
       [-0.18 ,  0.324]])

In [42]:
arr.repeat(2) # without `axis`, array is flattened first

array([ 0.295,  0.295,  1.506,  1.506, -0.18 , -0.18 ,  0.324,  0.324])

In [43]:
arr.repeat([2, 3], axis=0)

array([[ 0.295,  1.506],
       [ 0.295,  1.506],
       [-0.18 ,  0.324],
       [-0.18 ,  0.324],
       [-0.18 ,  0.324]])

In [44]:
arr.repeat([2, 3], axis=1)

array([[ 0.295,  0.295,  1.506,  1.506,  1.506],
       [-0.18 , -0.18 ,  0.324,  0.324,  0.324]])

In [45]:
arr

array([[ 0.295,  1.506],
       [-0.18 ,  0.324]])

In [46]:
np.tile(arr, 2)

array([[ 0.295,  1.506,  0.295,  1.506],
       [-0.18 ,  0.324, -0.18 ,  0.324]])

In [47]:
arr

array([[ 0.295,  1.506],
       [-0.18 ,  0.324]])

In [48]:
np.tile(arr, (2, 1))

array([[ 0.295,  1.506],
       [-0.18 ,  0.324],
       [ 0.295,  1.506],
       [-0.18 ,  0.324]])

In [49]:
np.tile(arr, (3, 2))

array([[ 0.295,  1.506,  0.295,  1.506],
       [-0.18 ,  0.324, -0.18 ,  0.324],
       [ 0.295,  1.506,  0.295,  1.506],
       [-0.18 ,  0.324, -0.18 ,  0.324],
       [ 0.295,  1.506,  0.295,  1.506],
       [-0.18 ,  0.324, -0.18 ,  0.324]])

### Fancy Indexing Equivalents: `take` and `put`

In [50]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [51]:
arr.take(inds)

array([700, 100, 200, 600])

In [52]:
arr.put(inds, 42)

In [53]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [54]:
arr = np.random.randn(2, 4)
arr

array([[ 1.962,  0.925,  0.544,  0.118],
       [-0.904,  0.926,  0.69 ,  0.911]])

In [55]:
inds = [2, 0, 2, 1]
arr.take(inds, axis=1)

array([[ 0.544,  1.962,  0.544,  0.925],
       [ 0.69 , -0.904,  0.69 ,  0.926]])

## A.2 Broadcasting

In [56]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [57]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [58]:
arr = np.random.randn(4, 3)
arr.mean(0)

array([-0.607,  0.351,  0.448])

In [59]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 1.517, -0.216,  0.438],
       [-1.338,  0.536,  1.259],
       [-0.207, -0.398, -0.514],
       [ 0.028,  0.078, -1.184]])

In [60]:
demeaned.mean(0)

array([ 0.,  0.,  0.])

In [61]:
# subtracting mean along rows is a bit harder:
arr

array([[ 0.91 ,  0.135,  0.886],
       [-1.945,  0.887,  1.707],
       [-0.814, -0.047, -0.066],
       [-0.579,  0.429, -0.736]])

In [62]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [63]:
row_means.reshape((4, 1))

array([[ 0.644],
       [ 0.216],
       [-0.309],
       [-0.295]])

In [64]:
demeaned = arr - row_means.reshape((4, 1))
demeaned

array([[ 0.266, -0.508,  0.242],
       [-2.161,  0.671,  1.491],
       [-0.505,  0.262,  0.243],
       [-0.284,  0.724, -0.441]])

In [65]:
demeaned.mean(1)

array([-0., -0.,  0., -0.])

### Broadcasting Over Other Axes

In [66]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

In [67]:
arr_1d = np.random.normal(size=3)
arr_1d[:, np.newaxis]

array([[-0.357],
       [ 0.935],
       [ 0.815]])

In [68]:
arr_1d[np.newaxis, :]

array([[-0.357,  0.935,  0.815]])

In [69]:
arr = np.random.randn(3, 4, 5)
depth_means = arr.mean(2)
depth_means

array([[ 0.817,  0.3  , -0.254, -0.131],
       [-0.13 , -0.357, -0.32 ,  0.075],
       [ 0.016, -0.859,  1.09 , -0.12 ]])

In [70]:
depth_means.shape

(3, 4)

In [71]:
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[-0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0., -0., -0.,  0.]])

In [72]:
def demean_axis(arr, axis=0):
    means = arr.means(axis)
    
    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

### Setting Array Values by Broadcasting

In [73]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [74]:
col = np.array([1.28, 0.42, 0.44, 1.6])
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [ 0.42,  0.42,  0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [75]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## A.4 Advanced `ufunc` Usage

### `ufunc` Instance Methods

In [76]:
arr = np.arange(10)
np.add.reduce(arr)

45

In [77]:
arr.sum()

45

In [78]:
np.random.seed(12346)
arr = np.random.randn(5, 5)
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [79]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True], dtype=bool)

In [80]:
(arr[:, :-1] < arr[:, 1:]).all(axis=1) # equivalent

array([ True, False,  True, False,  True], dtype=bool)

In [81]:
arr = np.arange(15).reshape(3, 5)
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [82]:
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [83]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [84]:
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [85]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8]) # like `pd.groupby`

array([10, 18, 17])

In [86]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [87]:
np.add.reduceat(arr, [0, 2, 4], axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]])

### Writing New `ufunc`s in Python

In [88]:
def add_elements(x, y):
    return x + y

add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [89]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.])

In [90]:
arr = np.random.randn(10_000)

%timeit add_them(arr, arr)

2.18 ms ± 157 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [91]:
%timeit np.add(arr, arr)

3.28 µs ± 34.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## A.5 Structured and Record Arrays

In [92]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([( 1.5  ,  6), ( 3.142, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [93]:
sarr[0]

( 1.5, 6)

In [94]:
sarr[0]['y']

6

In [95]:
sarr.dtype.names

('x', 'y')

In [96]:
sarr['x'] # strided view returned (no copying!)

array([ 1.5  ,  3.142])

### Nested dtypes and Multidimensional Fields

In [97]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [98]:
arr[0]['x']

array([0, 0, 0])

In [99]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [100]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']

array([( 1.,  2.), ( 3.,  4.)],
      dtype=[('a', '<f8'), ('b', '<f4')])

In [101]:
data['y']

array([5, 6], dtype=int32)

In [102]:
data['x']['a']

array([ 1.,  3.])

## A.6 More About Sorting

In [103]:
arr = np.random.randn(6)
arr.sort() # in-place
arr

array([-1.082,  0.376,  0.801,  1.14 ,  1.289,  1.841])

In [104]:
arr = np.random.randn(3, 5)
arr

array([[-0.332, -1.471,  0.871, -0.085, -1.133],
       [-1.011, -0.344,  2.171,  0.123, -0.019],
       [ 0.177,  0.742,  0.855,  1.038, -0.329]])

In [105]:
arr[:, 0].sort() # Sort first column values in-place
arr

array([[-1.011, -1.471,  0.871, -0.085, -1.133],
       [-0.332, -0.344,  2.171,  0.123, -0.019],
       [ 0.177,  0.742,  0.855,  1.038, -0.329]])

In [106]:
arr = np.random.randn(5)
arr

array([-1.118, -0.242, -2.005,  0.738, -1.061])

In [107]:
np.sort(arr) # produces a sorted copy

array([-2.005, -1.118, -1.061, -0.242,  0.738])

In [108]:
arr

array([-1.118, -0.242, -2.005,  0.738, -1.061])

In [109]:
arr = np.random.randn(3, 5)
arr

array([[ 0.595, -0.268,  1.339, -0.187,  0.911],
       [-0.322,  1.005, -0.517,  1.193, -0.199],
       [ 0.397, -1.764,  0.607, -0.222, -0.217]])

In [110]:
arr.sort(axis=1)
arr

array([[-0.268, -0.187,  0.595,  0.911,  1.339],
       [-0.517, -0.322, -0.199,  1.005,  1.193],
       [-1.764, -0.222, -0.217,  0.397,  0.607]])

In [111]:
arr[:, ::-1] # reverse hack

array([[ 1.339,  0.911,  0.595, -0.187, -0.268],
       [ 1.193,  1.005, -0.199, -0.322, -0.517],
       [ 0.607,  0.397, -0.217, -0.222, -1.764]])

### Indirect Sorts: `argsort` and `lexsort`

In [112]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0])

In [113]:
values[indexer]

array([0, 1, 2, 3, 5])

In [114]:
arr = np.random.randn(3, 5)
arr[0] = values
arr

array([[ 5.   ,  0.   ,  1.   ,  3.   ,  2.   ],
       [-0.364, -0.138,  2.178, -0.473,  0.836],
       [-0.209,  0.232,  0.728, -1.392,  1.996]])

In [115]:
arr[:, arr[0].argsort()]

array([[ 0.   ,  1.   ,  2.   ,  3.   ,  5.   ],
       [-0.138,  2.178,  0.836, -0.473, -0.364],
       [ 0.232,  0.728,  1.996, -1.392, -0.209]])

In [116]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [117]:
list(zip(last_name[sorter], first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### Alternative Sort Algorithms

In [118]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
key = np.array([2, 2, 1, 1, 1])
# 'mergesort' is the only available "stable" sort algorithm that preserves relative position of equal elements
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [119]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

### Partially Sorting Arrays

In [120]:
np.random.seed(12345)
arr = np.random.randn(20)
arr

array([-0.205,  0.479, -0.519, -0.556,  1.966,  1.393,  0.093,  0.282,
        0.769,  1.246,  1.007, -1.296,  0.275,  0.229,  1.353,  0.886,
       -2.002, -0.372,  1.669, -0.439])

In [121]:
np.partition(arr, 3) # first three elements in the result are the smallest three values in no particular order

array([-2.002, -1.296, -0.556, -0.519, -0.372, -0.439, -0.205,  0.282,
        0.769,  0.479,  1.007,  0.093,  0.275,  0.229,  1.353,  0.886,
        1.393,  1.966,  1.669,  1.246])

In [122]:
indices = np.argpartition(arr, 3)
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9])

In [123]:
arr.take(indices)

array([-2.002, -1.296, -0.556, -0.519, -0.372, -0.439, -0.205,  0.282,
        0.769,  0.479,  1.007,  0.093,  0.275,  0.229,  1.353,  0.886,
        1.393,  1.966,  1.669,  1.246])

### `numpy.searchsorted`: Finding Elements in a Sorted Array

In [124]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

3

In [125]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])

In [126]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])

array([0, 3])

In [127]:
arr.searchsorted([0, 1], side='right')

array([3, 7])

In [128]:
data = np.floor(np.random.uniform(0, 10_000, size=50))
bins = np.array([0, 100, 1_000, 5_000, 10_000])
data

array([ 9940.,  6768.,  7908.,  1709.,   268.,  8003.,  9037.,   246.,
        4917.,  5262.,  5963.,   519.,  8950.,  7282.,  8183.,  5002.,
        8101.,   959.,  2189.,  2587.,  4681.,  4593.,  7095.,  1780.,
        5314.,  1677.,  7688.,  9281.,  6094.,  1501.,  4896.,  3773.,
        8486.,  9110.,  3838.,  3154.,  5683.,  1878.,  1258.,  6875.,
        7996.,  5735.,  9732.,  6340.,  8884.,  4954.,  3516.,  7142.,
        5039.,  2256.])

In [129]:
labels = bins.searchsorted(data)
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3, 4,
       3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 3,
       3, 4, 4, 3])

In [131]:
import pandas as pd
pd.Series(data).groupby(labels).mean()

2     498.000000
3    3064.277778
4    7389.035714
dtype: float64

## A.7 Writing Fast NumPy Functions with Numba

In [132]:
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

x = np.random.randn(10_000_000)
y = np.random.randn(10_000_000)

%timeit mean_distance(x, y)

3.44 s ± 98.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [133]:
%timeit (x - y).mean()

38 ms ± 2.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [134]:
import numba as nb

numba_mean_distance = nb.jit(mean_distance)
%timeit numba_mean_distance(x, y)

14.6 ms ± 723 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [135]:
# can also use decorators:

@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

%timeit mean_distance(x, y)

13.9 ms ± 68.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Creating Custom `numpy.ufunc` Objects with Numba

In [136]:
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x + y

x = np.arange(10)
nb_add(x, x)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [141]:
nb_add.accumulate(x, 0)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## A.8 Advanced Array Input and Output

### Memory-Mapped Files

In [142]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10_000, 10_000))
mmap

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [143]:
section = mmap[:5]

In [144]:
section[:] = np.random.randn(5, 10_000)
mmap.flush()
mmap

memmap([[ 1.371,  0.931,  0.606, ..., -0.621, -0.468,  0.479],
        [ 0.423,  0.831,  0.7  , ...,  1.288,  0.589, -1.428],
        [ 2.16 , -1.246,  2.445, ...,  0.869,  0.28 ,  2.13 ],
        ..., 
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ]])

In [145]:
del mmap

In [146]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10_000, 10_000))
mmap

memmap([[ 1.371,  0.931,  0.606, ..., -0.621, -0.468,  0.479],
        [ 0.423,  0.831,  0.7  , ...,  1.288,  0.589, -1.428],
        [ 2.16 , -1.246,  2.445, ...,  0.869,  0.28 ,  2.13 ],
        ..., 
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  0.   , ...,  0.   ,  0.   ,  0.   ]])

## A.9 Performance Tips

### The Importance of Contiguous Memory

In [147]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [148]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [149]:
arr_f.flags.f_contiguous

True

In [151]:
%timeit arr_c.sum(1)

437 µs ± 45.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [152]:
%timeit arr_f.sum(1) # slower, since summing rows (along columns=axis-1), but ordered in memory by column-first

623 µs ± 38.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [153]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [154]:
arr_c[:50].flags.contiguous

True

In [157]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False