## 4.17 Problems

### Matrix-Vector Multiplication

**Problem 4.17.1:** Compute the following matrix-vector products (without a computer):  

1) $\begin{bmatrix}1 &1\\1 &-1\end{bmatrix} * \begin{bmatrix}0.5\\0.5\end{bmatrix}$

$\begin{bmatrix}1\\0\end{bmatrix}$

2) $\begin{bmatrix}0 &0\\0 &1\end{bmatrix} * \begin{bmatrix}1.2\\4.44\end{bmatrix}$

$\begin{bmatrix}0\\4.44\end{bmatrix}$

3) $\begin{bmatrix}1 &2 &3\\2 &3 &4\\3 &4 &5\end{bmatrix} * \begin{bmatrix}1\\2\\3\end{bmatrix}$

$\begin{bmatrix}14\\20\\26\end{bmatrix}$

**Problem 4.17.2:** What $2 \times 2$ matrix $M$ satisfies $M * [x, y] = [y, x]$ for all vectors $[x, y]$?

$M = \begin{bmatrix}0 &1\\1 &0\end{bmatrix}$

**Problem 4.17.3:** What $3 \times 3$ matrix $M$ satisfies $M * [x, y, z] = [z + x, y, x]$ for all vectors $[x, y, z]$?

$M = \begin{bmatrix}1 &0 &1\\0 &1 &0\\1 &0 &0\end{bmatrix}$

**Problem 4.17.4:** What $3 \times 3$ matrix $M$ satisfies $M * [x, y, z] = [2x, 4y, 3z]$ for all vectors $[x, y, z]$?

$M = \begin{bmatrix}2 &0 &0\\0 &4 &0\\0 &0 &3\end{bmatrix}$

### Matrix-matrix multiplication: dimensions of matrices

**Problem 4.17.5:** For each of the following problems, answer whether the given matrix-matrix product is valid or not. If it is valid, give the number of rows and the number of columns of the resulting matrix (you need not provide the matrix itself).  

1) $\begin{bmatrix}1 &1 &0\\1 &0 &1\end{bmatrix} \begin{bmatrix}2 &1 &1\\3 &1 &2\end{bmatrix}$

This product is invalid. $(2 \times 3) * (2 \times 3)$

2) $\begin{bmatrix}3 &3 &0\end{bmatrix} \begin{bmatrix}1 &4 &1\\1 &7 &2\end{bmatrix}$

This product is invalid. $(1 \times 3) * (2 \times 3)$

3) $\begin{bmatrix}3 &3 &0\end{bmatrix} \begin{bmatrix}1 &4 &1\\1 &7 &2\end{bmatrix}^T$

This product _is valid_. The resulting matrix has dimensions $1 \times 2$.

4) $\begin{bmatrix}1 &4 &1\\1 &7 &2\end{bmatrix} \begin{bmatrix}3 &3 &0\end{bmatrix}^T$

This product _is valid_. The resulting matrix has dimensions $2 \times 1$.

5) $\begin{bmatrix}1 &4 &1\\1 &7 &2\end{bmatrix} \begin{bmatrix}3 &3 &0\end{bmatrix}$

This product is invalid. $(2 \times 3) * (1 \times 3)$

6) $\begin{bmatrix}2 &1 &5\end{bmatrix} \begin{bmatrix}1 &6 &2\end{bmatrix}^T$

This product _is valid_. The resulting matrix has dimensions $1 \times 1$.

7) $\begin{bmatrix}2 &1 &5\end{bmatrix}^T \begin{bmatrix}1 &6 &2\end{bmatrix}$

This product _is valid_. The resulting matrix has dimensions $3 \times 3$.

In [1]:
import numpy as np
np.array([[2, 1, 5]]).T.dot(np.array([[1, 6, 2]]))

array([[ 2, 12,  4],
       [ 1,  6,  2],
       [ 5, 30, 10]])

## Matrix-matrix multiplication practice

**Problem 4.17.6:** Compute:

1) $\begin{bmatrix}2 &3\\4 &2\end{bmatrix} \begin{bmatrix}1 &2\\2 &3\end{bmatrix}$

$\begin{bmatrix}8 &13\\8 &14\end{bmatrix}$

2) $\begin{bmatrix}2 &4 &1\\3 &0 &-1\end{bmatrix} \begin{bmatrix}1 &2 &0\\5 &1 &1\\2 &3 &0\end{bmatrix}$

$\begin{bmatrix}24 &11 &4\\1 &3 &0\end{bmatrix}$

3) $\begin{bmatrix}2 &2 &1\end{bmatrix} \begin{bmatrix}3 &1\\-2 &6\\1 &-1\end{bmatrix}$

$\begin{bmatrix}3 &13\end{bmatrix}$

4) $\begin{bmatrix}1 &2 &3\end{bmatrix} \begin{bmatrix}1\\2\\3\end{bmatrix}$

14

5) $\begin{bmatrix}1\\2\\3\end{bmatrix} \begin{bmatrix}1 &2 &3\end{bmatrix}$

$\begin{bmatrix}1 &2 &3\\2 &4 &6\\3 &6 &9\end{bmatrix}$

6) $\begin{bmatrix}4 &1 &-3\\2 &2 &-2\end{bmatrix}^T \begin{bmatrix}-1 &1\\1 &0\end{bmatrix}$

$\begin{bmatrix}-2 &4\\1 &1\\1 &-3\end{bmatrix}$

In [2]:
# Check all with numpy:

import numpy as np

print('1)\n', np.array([[2,3],[4,2]]).dot(np.array([[1,2],[2,3]])))
print('\n2)\n', np.array([[2,4,1],[3,0,-1]]).dot(np.array([[1,2,0],[5,1,1],[2,3,0]])))
print('\n3)\n', np.array([[2,2,1]]).dot(np.array([[3,1],[-2,6],[1,-1]])))
print('\n4)\n', np.array([[1,2,3]]).dot(np.array([[1,2,3]]).T))
print('\n5)\n', np.array([[1,2,3]]).T.dot(np.array([[1,2,3]])))
print('\n6)\n', np.array([[4,1,-3],[2,2,-2]]).T.dot(np.array([[-1,1],[1,0]])))

1)
 [[ 8 13]
 [ 8 14]]

2)
 [[24 11  4]
 [ 1  3  0]]

3)
 [[ 3 13]]

4)
 [[14]]

5)
 [[1 2 3]
 [2 4 6]
 [3 6 9]]

6)
 [[-2  4]
 [ 1  1]
 [ 1 -3]]


**Problem 4.17.7:** Let
    
$A = \begin{bmatrix}2 &0 &1 &5\\1 &-4 &6 &2\\3 &0 &-4 &2\\3 &4 &0 &-2\end{bmatrix}$

For each of the following values of the matrix $B$, compute $AB$ and $BA$, without a computer.

1) $B = \begin{bmatrix}0 &1 &0 &0\\0 &0 &1 &0\\0 &0 &0 &1\\1 &0 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}5 &2 &0 &1\\2 &1 &-4 &6\\2 &3 &0 &-4\\-2 &3 &4 &0\end{bmatrix}$
$BA = \begin{bmatrix}1 &-4 &6 &2\\3 &0 &-4 &2\\3 &4 &0 &-2\\2 &0 &1 &5\end{bmatrix}$

2) $B = \begin{bmatrix}0 &0 &0 &1\\0 &0 &1 &0\\0 &1 &0 &0\\1 &0 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}5 &1 &0 &2\\2 &6 &-4 &1\\2 &-4 &0 &3\\-2 &0 &4 &3\end{bmatrix}$
$BA = \begin{bmatrix}3 &4 &0 &-2\\3 &0 &-4 &2\\1 &-4 &6 &2\\2 &0 &1 &5\end{bmatrix}$

3) $B = \begin{bmatrix}0 &0 &0 &1\\0 &1 &0 &0\\1 &0 &0 &0\\0 &0 &1 &0\end{bmatrix}$

$AB = \begin{bmatrix}1 &0 &5 &2\\6 &-4 &2 &1\\-4 &0 &2 &3\\0 &4 &-2 &3\end{bmatrix}$
$BA = \begin{bmatrix}3 &4 &0 &-2\\1 &-4 &6 &2\\2 &0 &1 &5\\3 &0 &-4 &2\end{bmatrix}$


In [3]:
# Check all with numpy:

import numpy as np

A = np.array([[2,0,1,5],[1,-4,6,2],[3,0,-4,2],[3,4,0,-2]])
for i, B in enumerate([np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]]),
          np.array([[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]),
          np.array([[0,0,0,1],[0,1,0,0],[1,0,0,0],[0,0,1,0]])]):
    print('\n' + str(i + 1) + ')\nAB=\n', A.dot(B))
    print('\nBA=\n', B.dot(A))


1)
AB=
 [[ 5  2  0  1]
 [ 2  1 -4  6]
 [ 2  3  0 -4]
 [-2  3  4  0]]

BA=
 [[ 1 -4  6  2]
 [ 3  0 -4  2]
 [ 3  4  0 -2]
 [ 2  0  1  5]]

2)
AB=
 [[ 5  1  0  2]
 [ 2  6 -4  1]
 [ 2 -4  0  3]
 [-2  0  4  3]]

BA=
 [[ 3  4  0 -2]
 [ 3  0 -4  2]
 [ 1 -4  6  2]
 [ 2  0  1  5]]

3)
AB=
 [[ 1  0  5  2]
 [ 6 -4  2  1]
 [-4  0  2  3]
 [ 0  4 -2  3]]

BA=
 [[ 3  4  0 -2]
 [ 1 -4  6  2]
 [ 2  0  1  5]
 [ 3  0 -4  2]]


**Problem 4.17.8:** Let $a$, $b$ be numbers and let $A = \begin{bmatrix}1 &a\\0 &1\end{bmatrix}$ and $B = \begin{bmatrix}1 &b\\0 &1\end{bmatrix}$.

1. What is $AB$? Write it in terms of $a$ and $b$.
    $AB = \begin{bmatrix}1 &b + a\\0 &1\end{bmatrix}$
2. Recall that, for a matrix $M$ and a nonnegative integer $k$, we denote by $M^{k}$ the $k$-fold product of $M$ with itself.  Plug in $1$ for $a$ in $A$. What is $A^2$, $A^3$? What is $A^n$ where $n$ is a positive integer?

Setting $a = 1$ in $A$, $A = \begin{bmatrix}1 &1\\0 &1\end{bmatrix}$.

$A^2 = \begin{bmatrix}1 &1\\0 &1\end{bmatrix} \begin{bmatrix}1 &1\\0 &1\end{bmatrix} = \begin{bmatrix}1 &2\\0 &1\end{bmatrix}$

$A^3 = \begin{bmatrix}1 &2\\0 &1\end{bmatrix} \begin{bmatrix}1 &1\\0 &1\end{bmatrix} = \begin{bmatrix}1 &3\\0 &1\end{bmatrix}$

$A^n = \begin{bmatrix}1 &2\\0 &1\end{bmatrix} \begin{bmatrix}1 &1\\0 &1\end{bmatrix} = \begin{bmatrix}1 &n\\0 &1\end{bmatrix}$

**Problem 4.17.9:** Let
$A = \begin{bmatrix}4 &2 &1 &-1\\1 &5 &-2 &3\\4 &4 &4 &0\\-1 &6 &2 &-5\end{bmatrix}$

For each of the following values of the matrix $B$, compute $AB$ and $BA$ without using a computer. 

a) $\begin{bmatrix}0 &0 &0 &0\\0 &0 &1 &0\\0 &0 &0 &0\\0 &0 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}0 &0 &2 &0\\0 &0 &5 &0 &0\\0 &0 &4 &0\\0 &0 &6 &0\end{bmatrix}$
$BA = \begin{bmatrix}0 &0 &0 &0\\4 &4 &4 &0\\0 &0 &0 &0\\0 &0 &0 &0\end{bmatrix}$

b) $\begin{bmatrix}0 &0 &0 &0\\0 &1 &0 &0\\0 &0 &0 &0\\0 &0 &1 &0\end{bmatrix}$

$AB = \begin{bmatrix}0 &2 &-1 &0\\0 &5 &3 &0 &0\\0 &4 &0 &0\\0 &6 &5 &0\end{bmatrix}$
$BA = \begin{bmatrix}0 &0 &0 &0\\1 &5 &2 &3\\0 &0 &0 &0\\4 &4 &4 &0\end{bmatrix}$

c) $\begin{bmatrix}1 &0 &0 &0\\1 &0 &0 &0\\0 &0 &0 &0\\0 &0 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}6 &0 &0 &0\\7 &0 &0 &0 &0\\8 &0 &0 &0\\5 &0 &0 &0\end{bmatrix}$
$BA = \begin{bmatrix}4 &2 &1 &-1\\4 &2 &1 &-1\\0 &0 &0 &0\\0 &0 &0 &0\end{bmatrix}$

d) $\begin{bmatrix}0 &1 &0 &1\\0 &0 &0 &0\\0 &0 &0 &0\\0 &1 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}0 &3 &0 &4\\0 &4 &0 &1\\0 &4 &0 &4\\0 &-6 &0 &1\end{bmatrix}$
$BA = \begin{bmatrix}0 &11 &0 &-2\\0 &0 &0 &0\\0 &0 &0 &0\\1 &5 &-2 &3\end{bmatrix}$

e) $\begin{bmatrix}0 &0 &0 &2\\0 &0 &0 &0\\0 &0 &0 &0\\0 &-3 &0 &0\end{bmatrix}$

$AB = \begin{bmatrix}0 &3 &0 &8\\0 &-9 &0 &2\\0 &0 &0 &8\\0 &15 &0 &-2\end{bmatrix}$
$BA = \begin{bmatrix}-2 &12 &4 &-10\\0 &0 &0 &0\\0 &0 &0 &0\\-3 &-15 &6 &-9\end{bmatrix}$

f) $\begin{bmatrix}-1 &0 &0 &0\\0 &2 &0 &0\\0 &0 &2 &0\\0 &0 &0 &3\end{bmatrix}$

$AB = \begin{bmatrix}-4 &4 &2 &-3\\-1 &10 &-4 &9\\-4 &8 &8 &0\\1 &12 &4 &-15\end{bmatrix}$
$BA = \begin{bmatrix}-4 &-2 &-1 &1\\2 &10 &-4 &6\\8 &8 &8 &0\\-3 &18 &6 &-15\end{bmatrix}$


In [4]:
# Check all with numpy:

import numpy as np

A = np.array([[4,2,1,-1],[1,5,-2,3],[4,4,4,0],[-1,6,2,-5]])
for label, B in zip(
        list('abcdef'),[np.array([[0,0,0,0],[0,0,1,0],[0,0,0,0],[0,0,0,0]]),
                        np.array([[0,0,0,0],[0,1,0,0],[0,0,0,0],[0,0,1,0]]),
                        np.array([[1,0,0,0],[1,0,0,0],[0,0,0,0],[0,0,0,0]]),
                        np.array([[0,1,0,1],[0,0,0,0],[0,0,0,0],[0,1,0,0]]),
                        np.array([[0,0,0,2],[0,0,0,0],[0,0,0,0],[0,-3,0,0]]),
                        np.array([[-1,0,0,0],[0,2,0,0],[0,0,2,0],[0,0,0,3]])]):
    print('\n' + label + ')\nAB=\n', A.dot(B))
    print('\nBA=\n', B.dot(A))


a)
AB=
 [[0 0 2 0]
 [0 0 5 0]
 [0 0 4 0]
 [0 0 6 0]]

BA=
 [[0 0 0 0]
 [4 4 4 0]
 [0 0 0 0]
 [0 0 0 0]]

b)
AB=
 [[ 0  2 -1  0]
 [ 0  5  3  0]
 [ 0  4  0  0]
 [ 0  6 -5  0]]

BA=
 [[ 0  0  0  0]
 [ 1  5 -2  3]
 [ 0  0  0  0]
 [ 4  4  4  0]]

c)
AB=
 [[6 0 0 0]
 [6 0 0 0]
 [8 0 0 0]
 [5 0 0 0]]

BA=
 [[ 4  2  1 -1]
 [ 4  2  1 -1]
 [ 0  0  0  0]
 [ 0  0  0  0]]

d)
AB=
 [[ 0  3  0  4]
 [ 0  4  0  1]
 [ 0  4  0  4]
 [ 0 -6  0 -1]]

BA=
 [[ 0 11  0 -2]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 1  5 -2  3]]

e)
AB=
 [[ 0  3  0  8]
 [ 0 -9  0  2]
 [ 0  0  0  8]
 [ 0 15  0 -2]]

BA=
 [[ -2  12   4 -10]
 [  0   0   0   0]
 [  0   0   0   0]
 [ -3 -15   6  -9]]

f)
AB=
 [[ -4   4   2  -3]
 [ -1  10  -4   9]
 [ -4   8   8   0]
 [  1  12   4 -15]]

BA=
 [[ -4  -2  -1   1]
 [  2  10  -4   6]
 [  8   8   8   0]
 [ -3  18   6 -15]]


### Matrix-matrix multiplication: dimensions of matrices (revisited)

**Problem 4.17.10:** For each of the following problems, answer whether the given matrix-matrix product is valid or not. If it is valid, give the number of rows and the number of columns of the resulting matrix.

This is a dupe of problem 4.17.5.

### Column-vector and row-vector matrix multiplication

**Problem 4.17.11:** Compute the result of the following matrix multiplications.

a) $\begin{bmatrix}2 &3 &1\\1 &3 &4\end{bmatrix}\begin{bmatrix}2\\2\\3\end{bmatrix}$

$\begin{bmatrix}13\\20\end{bmatrix}$

b) $\begin{bmatrix}2 &4 &1\end{bmatrix}\begin{bmatrix}1 &2 &0\\5 &1 &1\\2 &3 &0\end{bmatrix}$

$\begin{bmatrix}24 &11 &4\end{bmatrix}$

c) $\begin{bmatrix}2 &1\end{bmatrix}\begin{bmatrix}3 &1 &5 &2\\-2 &6 &1 &-1\end{bmatrix}$

$\begin{bmatrix}4 &8 &11 &3\end{bmatrix}$

d) $\begin{bmatrix}1 &2 &3 &4\\1 &1 &3 &1\end{bmatrix}\begin{bmatrix}1\\2\\3\\4\end{bmatrix}$

$\begin{bmatrix}30\\16\end{bmatrix}$

e) $\begin{bmatrix}4\\1\\-3\end{bmatrix}^T\begin{bmatrix}-1 &1 &1\\1 &0 &2\\0 &1 &-1\end{bmatrix}$

$\begin{bmatrix}-3 &1 &9\end{bmatrix}$

In [5]:
# Check all:

import numpy as np

print('a)\n', np.array([[2,3,1],[1,3,4]]).dot(np.array([[2,2,3]]).T))
print('\nb)\n', np.array([[2,4,1]]).dot(np.array([[1,2,0],[5,1,1],[2,3,0]])))
print('\nc)\n', np.array([[2,1]]).dot(np.array([[3,1,5,2],[-2,6,1,-1]])))
print('\nd)\n', np.array([[1,2,3,4],[1,1,3,1]]).dot(np.array([[1,2,3,4]]).T))
print('\ne)\n', np.array([[4,1,-3]]).dot(np.array([[-1,1,1],[1,0,2],[0,1,-1]])))

a)
 [[13]
 [20]]

b)
 [[24 11  4]]

c)
 [[ 4  8 11  3]]

d)
 [[30]
 [16]]

e)
 [[-3  1  9]]


## Matrix Class

**Problem 2.14.10:** Download the file mat.py to your computer, and edit it. Fill in the procedure definitions and test the doctests with  
`python3 -m doctest mat.py`.

In [28]:
!python3 -m doctest ../mat.py
# No output means success!

### Matrix-vector and vector-matrix multiplication definitions in Python

**Problem 4.17.13:** Write the procedure `lin_comb_mat_vec_mult(M, v)`, which multiplies `M` times `v` using the linear combination definition. For this problem, the only operation on `v` you are allowed is getting the value of an entry using brackets: `v[k]`. The vector returned must be computed as a linear combination.

In [7]:
import sys
sys.path.append('../')

from vec import Vec
from mat import Mat
from matutil import mat2rowdict, mat2coldict, rowdict2mat, coldict2mat, listlist2mat
from vecutil import list2vec

def lin_comb_mat_vec_mult(M, v):
    return Vec(M.D[0], {row_label: sum(v[col_label] * M[row_label, col_label] for col_label in v.D) for row_label in M.D[0]})

M_1 = listlist2mat([[-1, 1, 2], [1, 2, 3], [2, 2, 1]])
v_1 = list2vec([1, 2, 0])

print(lin_comb_mat_vec_mult(M_1, v_1))


 0 1 2
------
 1 5 6


**Problem 4.17.14:** Write the procedure `lin_comb_vec_mat_mult(v, M)`, which multiplies `v` times `M` using the linear combination definition. For this problem, the only operation on `v` you are allowed is getting the value of an entry using brackets: `v[k]`. The vector returned must be computed as a linear combination.

In [8]:
def lin_comb_vec_mat_mult(v, M):
    return Vec(M.D[1], {col_label: sum(v[row_label] * M[row_label, col_label] for row_label in v.D) for col_label in M.D[1]})

v_2 = list2vec([4, 3, 2, 1])
M_2 = listlist2mat([[-5, 10], [-4, 8], [-3, 6], [-2, 4]])
print(lin_comb_vec_mat_mult(v_2, M_2))


   0  1
-------
 -40 80


**Problem 4.17.15:** Write the procedure `dot_product_mat_vec_mult(M, v)`, which multiplies `M` times `v` using the dot-product definition. For this problem, the only operation on `v` you are allowed is taking the dot-product of `v` and another vector: `v: u*v` or `v*u`.

In [9]:
def dot_product_mat_vec_mult(M, v):
    return Vec(M.D[0], {row_label: v * row for row_label, row in mat2rowdict(M).items()})

print(dot_product_mat_vec_mult(M_1, v_1))


 0 1 2
------
 1 5 6


**Problem 4.17.15:** Write the procedure `dot_product_vec_mat_mult(M, v)`, which multiplies `v` times `M` using the dot-product definition. For this problem, the only operation on `v` you are allowed is taking the dot-product of `v` and another vector: `v: u*v` or `v*u`.

In [10]:
def dot_product_vec_mat_mult(v, M):
    return Vec(M.D[1], {col_label: v * col for col_label, col in mat2coldict(M).items()})

print(lin_comb_vec_mat_mult(v_2, M_2))


   0  1
-------
 -40 80


### Matrix-matrix multiplication definitions in Python

**Problem 4.17.17:** Write `Mv_mat_mat_mult(A, B)` to compute the matrix-matrix product $A * B$, using the matrix-vector multiplication definition of matrix-matrix multiplication. For this procedure, the only operation you are allowed to do on $A$ is matrix-vector multiplication, using the `*` operator `A*v`.

In [11]:
def Mv_mat_mat_mult(A, B):
    return Mat((A.D[0], B.D[1]), {(row_label, col_label): val for col_label, b_col in mat2coldict(B).items() for row_label, val in (A * b_col).f.items()})

A = listlist2mat([[4,2,1,-1],[1,5,-2,3],[4,4,4,0],[-1,6,2,-5]])
B = listlist2mat([[-1,0,0,0],[0,2,0,0],[0,0,2,0],[0,0,0,3]])

print(Mv_mat_mat_mult(A, B))

# expected (from previous problem)
# [[ -4   4   2  -3]
#  [ -1  10  -4   9]
#  [ -4   8   8   0]
#  [  1  12   4 -15]]

print(Mv_mat_mat_mult(B, A))

# expected (from previous problem)
# [[ -4  -2  -1   1]
#  [  2  10  -4   6]
#  [  8   8   8   0]
#  [ -3  18   6 -15]]


        0  1  2   3
     --------------
 0  |  -4  4  2  -3
 1  |  -1 10 -4   9
 2  |  -4  8  8   0
 3  |   1 12  4 -15


        0  1  2   3
     --------------
 0  |  -4 -2 -1   1
 1  |   2 10 -4   6
 2  |   8  8  8   0
 3  |  -3 18  6 -15



**Problem 4.17.18:** Write `vM_mat_mat_mult(A, B)` to compute the matrix-matrix product $A * B$, using the vector-matrix multiplication definition of matrix-matrix multiplication. For this procedure, the only operation you are allowed to do on $B$ is vector-matrix multiplication, using the `*` operator `v*B`.

In [12]:
def vM_mat_mat_mult(A, B):
    return Mat((A.D[0], B.D[1]), {(row_label, col_label): val for row_label, b_row in mat2rowdict(A).items() for col_label, val in (b_row * B).f.items()})

print(vM_mat_mat_mult(A, B))
print(vM_mat_mat_mult(B, A))


        0  1  2   3
     --------------
 0  |  -4  4  2  -3
 1  |  -1 10 -4   9
 2  |  -4  8  8   0
 3  |   1 12  4 -15


        0  1  2   3
     --------------
 0  |  -4 -2 -1   1
 1  |   2 10 -4   6
 2  |   8  8  8   0
 3  |  -3 18  6 -15



### Dot products via matrix-matrix multiplication

**Problem 4.17.19:** Let $A$ be a matrix whose column labels are countries and whose row labels are votes taken in the United Nations (UN), where $A[i, j]$ is $+1$ or $-1$ or $0$ depending on whether country $j$ votes in favor of or against or neighter in vote $i$.  
As in the politics lab, we can compare countries by comparing their voting records. Let $M = A^TA$. Then $M$'s row and column labels are countries, and $M[i,j]$ is the dot-product of country $i$'s voting record with country $j$'s voting record.  
The provided file `UN_voting_data.txt` has one line per country. The line consists of the country name, followed by $+1$'s, $-1$'s, and zeroes, separated by spaces. Read in the data and form the matrix $A$. Then form the matrix $M = A^TA$.  
Use $M$ to answer the following questions.

1. Which pair of countries are most opposed? (They have the most negative dot-product.)
1. What are the ten most opposed pairs of countries?
1. Which pair of distinct countries are in the greatest agreement?

In [13]:
f = open('UN_voting_data.txt')
l = list(f)

In [14]:
def create_voting_matrix(strlist):
    return coldict2mat({s.split()[0]: list2vec([int(v) for v in s.split()[1:]]) for s in strlist})

A = create_voting_matrix(l)
print(list(A.f.items())[0])

((0, 'Ireland'), 0)


In [15]:
A_T = A.transpose()

In [16]:
M = A_T * A

In [17]:
# some sanity checking...
import math
math.sqrt(len(M.f))

206.0

In [18]:
len(l)

206

In [19]:
len(l[0]) # this is the max magnitude of agreement or disagreement possible (if there was no obstaining from either country)

10916

In [20]:
# Question 1: most opposed
most_opposed_countries = min(M.f, key=M.f.get)
most_opposed_countries

('Belarus', 'United_States_of_America')

In [21]:
'Most opposed countries: ' + str(most_opposed_countries) + ' with a cumulative disagreement of: ' + str(M[most_opposed_countries])

"Most opposed countries: ('Belarus', 'United_States_of_America') with a cumulative disagreement of: -1927"

In [22]:
# We would expect the max agreement to be between the country with the most non-obstaining (non-zero) votes,
# with itself (along the diagonal):
country_with_most_non_obstaining_votes = max(M.f, key=M.f.get)
country_with_most_non_obstaining_votes

('Philippines', 'Philippines')

In [23]:
# this is the actual maximum agreement in this dataset...
M[country_with_most_non_obstaining_votes]

4690

In [24]:
# so another way of considering the most _disagreeing_ countries is normalized to the true maximum _agreement_:
abs(M[most_opposed_countries] / M[country_with_most_non_obstaining_votes])

0.41087420042643924

In [25]:
# Question 2: ten most opposed countries:
M_copy = M.copy()

ten_most_opposed_countries = []
for i in range(10):
    most_opposed = min(M_copy.f, key=M_copy.f.get)
    ten_most_opposed_countries.append(most_opposed)
    del(M_copy.f[most_opposed])
    del(M_copy.f[(most_opposed[1], most_opposed[0])]) # delete the other of the pair (across the diagonal)

ten_most_opposed_countries

[('Belarus', 'United_States_of_America'),
 ('Syria', 'United_States_of_America'),
 ('Cuba', 'United_States_of_America'),
 ('Algeria', 'United_States_of_America'),
 ('Viet_Nam', 'United_States_of_America'),
 ('Libya', 'United_States_of_America'),
 ('Guinea', 'United_States_of_America'),
 ('Mongolia', 'United_States_of_America'),
 ('Mali', 'United_States_of_America'),
 ('Sudan', 'United_States_of_America')]

In [26]:
# Question 3: Which pair of distinct countries are in the greatest agreement?

# delete diagonal entries first
M_copy = M.copy()
for country in M.D[0]:
    del(M_copy.f[(country, country)])

most_aligned_countries = max(M_copy.f, key=M_copy.f.get)
'Most aligned countries: ' + str(most_aligned_countries) + ' with cumulative agreement of: ' + str(M[most_aligned_countries])

"Most aligned countries: ('Philippines', 'Thailand') with cumulative agreement of: 4229"

### Comprehension practice

**Problem 4.17.20:** Write the one-line procedure `dictlist_helper(dlist, k)` with the following spec:  
* _input:_ a list `dlist` of dictionaries which all have the same keys, and a key `k`
* _output:_ the list whose $i^{th}$ element is the value corresponding to the key `k` in the $i^{th}$ dictionary of `dlist`
* _example:_ With inputs `dlist=[{'a':'apple', 'b':'bear'}, {'a':1, 'b':2}]` and `k='a'`, the output is `['apple', 1]`

The procedure should use a comprehension.

In [27]:
def dictlist_helper(dlist, k):
    return [d[k] for d in dlist]

dictlist_helper([{'a':'apple', 'b':'bear'}, {'a':1, 'b':2}], 'a')

['apple', 1]

### The inverse of a $2 \times 2$ matrix

**Problem 4.17.21:**    

1. Use a formula given in the text to solve the linear system $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}\begin{bmatrix}x_1\\x_2\end{bmatrix} = \begin{bmatrix}1\\0\end{bmatrix}$.  
  
  $3x_1 + 4x_2 = 1\\2x_1 + 1x_2 = 0$
  
  $\implies$
  
  $x_2 = -2x_1 \implies 3x_1 + 4(-2x_1) = 1 \implies x_1 = -\frac{1}{5}$, and  
  $x_2 = \frac{2}{5}$
  
  $\begin{bmatrix}x_1\\x_2\end{bmatrix} = \begin{bmatrix}-\frac{1}{5}\\\frac{2}{5}\end{bmatrix}$

2. Use the formula to solve the linear system $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}\begin{bmatrix}y_1\\y_2\end{bmatrix} = \begin{bmatrix}0\\1\end{bmatrix}$.

  $3y_1 + 4y_2 = 0\\2y_1 + 1y_2 = 1$

  $\implies$

  $y_2 = -\frac{3}{4}y_1 \implies 2y_1 - \frac{3}{4}y_1 = 1 \implies y_1 = \frac{4}{5}$, and  
  $y_2 = -\frac{3}{5}$

  $\begin{bmatrix}y_1\\y_2\end{bmatrix} = \begin{bmatrix}\frac{4}{5}\\-\frac{3}{5}\end{bmatrix}$

3. Use your solutions to find a $2 \times 2$ matrix $M$ such that $\begin{bmatrix} 3 &4\\2 &1\end{bmatrix}$ times $M$ is an identity matrix.

  $M = \begin{bmatrix}x_1 &y_1\\x_2 &y_2\end{bmatrix} = \begin{bmatrix}-\frac{1}{5} &\frac{4}{5}\\\frac{2}{5} &-\frac{3}{5}\end{bmatrix}$

4. Calculate $M$ times $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}$ and calculate $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}$ times $M$, and use _Corollary 4.13.19_ to decide whether $M$ is the inverse of $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}$. Explain your answer.

  $\begin{bmatrix}-\frac{1}{5} &\frac{4}{5}\\\frac{2}{5} &-\frac{3}{5}\end{bmatrix} \begin{bmatrix}3 &4\\2 &1\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$

  $\begin{bmatrix}3 &4\\2 &1\end{bmatrix} \begin{bmatrix}-\frac{1}{5} &\frac{4}{5}\\\frac{2}{5} &-\frac{3}{5}\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$

  _Corollary 4.13.19_ states that matrices $A$ and $B$ are inverses of each other if and only if both $AB$ and $BA$ are identity matrices.  Thus, $M$ is the inverse of $\begin{bmatrix}3 &4\\2 &1\end{bmatrix}$.

### Matrix inverse criterion

**Problem 4.17.22:** For each of the parts below, use _Corollary 4.13.19_ to demonstrate that the pair of matrices given are or are not inverses of each other.

1. $\begin{bmatrix}5 &1\\9 &2\end{bmatrix}$,$\begin{bmatrix}2 &-1\\-9 &5\end{bmatrix}$ over $\mathbb{R}$

  $\begin{bmatrix}5 &1\\9 &2\end{bmatrix} \begin{bmatrix}2 &-1\\-9 &5\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$
  
  $\begin{bmatrix}2 &-1\\-9 &5\end{bmatrix} \begin{bmatrix}5 &1\\9 &2\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$

  These matrices _are_ inverses of each other.

2. $\begin{bmatrix}2 &0\\0 &1\end{bmatrix}$,$\begin{bmatrix}\frac{1}{2} &0\\0 &1\end{bmatrix}$ over $\mathbb{R}$

  $\begin{bmatrix}2 &0\\0 &1\end{bmatrix} \begin{bmatrix}\frac{1}{2} &0\\0 &1\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$
  
  $\begin{bmatrix}\frac{1}{2} &0\\0 &1\end{bmatrix} \begin{bmatrix}2 &0\\0 &1\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$

  These matrices _are_ inverses of each other.

3. $\begin{bmatrix}3 &1\\0 &2\end{bmatrix}$,$\begin{bmatrix}1 &\frac{1}{6}\\-2 &\frac{1}{2}\end{bmatrix}$ over $\mathbb{R}$

  $\begin{bmatrix}3 &1\\0 &2\end{bmatrix} \begin{bmatrix}1 &\frac{1}{6}\\-2 &\frac{1}{2}\end{bmatrix} = \begin{bmatrix}1 &1\\-4 &1\end{bmatrix}$
  
  $\begin{bmatrix}1 &\frac{1}{6}\\-2 &\frac{1}{2}\end{bmatrix} \begin{bmatrix}3 &1\\0 &2\end{bmatrix} = \begin{bmatrix}3 &\frac{4}{3}\\-6 &-1\end{bmatrix}$
  
  These matrices _are not_ inverses of each other.
  
4. $\begin{bmatrix}1 &0 &1\\0 &1 &0\end{bmatrix}$,$\begin{bmatrix}0 &1\\0 &1\\1 &1\end{bmatrix}$ over $GF(2)$

  $\begin{bmatrix}1 &0 &1\\0 &1 &0\end{bmatrix} \begin{bmatrix}0 &1\\0 &1\\1 &1\end{bmatrix} = \begin{bmatrix}1 &0\\0 &1\end{bmatrix}$
  
  $\begin{bmatrix}0 &1\\0 &1\\1 &1\end{bmatrix} \begin{bmatrix}1 &0 &1\\0 &1 &0\end{bmatrix} = \begin{bmatrix}0 &1 &0\\0 &1 &0\\1 &1 &1\end{bmatrix}$

  These matrices _are not_ inverses of each other.


**Problem 4.17.23:**  Specify a function $f$ (by domain, co-domain, and rule) that is invertible but such that there is no matrix $A$ such that $f(\boldsymbol{x}) = A\boldsymbol{x}$.

Define $f: \mathbb{R}^N \to \mathbb{R}^M$, where  $f(\boldsymbol{x}) = \{x_i^3, x_i \in \boldsymbol{x}\}$. Then $g(\boldsymbol{x}) = \{x_i^\frac{1}{3}, x_i \in \boldsymbol{x}\}$ is the inverse of $f$, but there is no matrix $A$ such that $f(\boldsymbol{x}) = A\boldsymbol{x}$.